frontend/urls.py
from django.conf.urls.defaults import patterns, url, include
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('frontend.views',
    url(r'^$', 'home', name='frontend_home'),
    url(r'^about/$', direct_to_template, {'template': 'frontend/about.html'}, name='frontend_about'),
    url(r'^contact/$', direct_to_template , {'template': 'frontend/contact.html'}, name='frontend_contact'),
    url(r'^vietnam/', 'local', name='frontend_local'),
    url(r'^testnewpin/$', direct_to_template, {'template':'frontend/testnewpin.html'}),
    url(r'^accounts/error/$', 'accountserror', name='frontend_accountserror'),
    url(r'^accounts/login/$', direct_to_template, {'template': 'frontend/accounts/login.html'}, name = 'frontend_accountslogin'),
    url(r'^accounts/logout/$', 'accountslogout', name = 'frontend_accountslogout'),
    url(r'^accounts/createuser/$', 'accountscreateuser', name='frontend_accountscreateuser'),
    url(r'', include('social_auth.urls')),
)

#    =========================
#    Ajax
#    =========================
urlpatterns += patterns('frontend.ajax',
    url(r'^ajax/pin/getthumbs/$', 'pingetthumbs', name='frontend_pingetthumbs'),
    url(r'^ajax/pin/new/$', 'pinnew', name='frontend_pinnew'),
    url(r'^ajax/pin/getdetails/(?P<id>\d+)/$', 'pingetdetails', name='frontend_pingetdetails'),
    url(r'^ajax/top/new/$', 'topnew', name='frontend_topnew'),
    url(r'^ajax/comment/new/$', 'commentnew', name='frontend_commentnew'),
    url(r'^ajax/location/getall/$', 'locationgetall', name='frontend_locationgetall'),
    url(r'^ajax/vote/new/$', 'votenew', name='frontend_votenew'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('frontend.urls')),
)

import os
if os.environ['SERVER_SOFTWARE'] == 'local':
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

frontend/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail import ImageField
import os
from datetime import datetime, timedelta
from utils import slugify

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	added = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	avatar = ImageField(upload_to='avatar', blank = True, null= True)

class Zoom(models.Model):
	name = models.CharField(max_length=50)
	def __unicode__(self):
		return self.name

def get_default_user():
	qs = User.objects.filter(username='nguyenivan')
	if qs:
		return qs[0]
	else:
		return None

from frontend.utils import remove_accent
import re	

class Location(models.Model):
	name = models.CharField(max_length=100, blank = True)
	local_name = models.CharField(max_length=100)
	latlng = models.CharField(max_length=50)
	zoom = models.ForeignKey(Zoom, default = 2)
	superordinate = models.ForeignKey('self', blank = True, null = True)
	owner = models.ForeignKey(User, default = 1)
	added = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	slug = models.SlugField(blank = True)
	path = models.CharField(max_length=256, blank = True)
	crumb = models.CharField(max_length=512, blank = True)
	def __unicode__(self):
		return self.name
	
	def get_sorted_tops(self):
		last24h = datetime.strftime( datetime.now() - timedelta(days=1), '%Y-%m-%d')
		q1 = Top.objects.filter( updated__gte = last24h, location = self).order_by('-updated')
		q2 = Top.objects.filter( updated__lt = last24h, location = self).order_by('-vote_count')
		return chain (q1, q2)
	
	def save(self, *args, **kwargs):
		if not self.name:
			self.name=remove_accent(self.local_name.encode('utf-8'))
		if not self.slug:
			self.slug =  ''.join(re.findall('\w',self.name)).lower() 
		supers = []
		slugs = []
		count = 0
		loc = self
		while loc and count < 4: #prevent infinite loop
			count+=1
			supers.insert(0,loc)
			slugs.insert(0,loc.slug)
			loc = loc.superordinate
		self.path = '/vietnam/%s/' % '/'.join(slugs)
		links = ['<a href="%s">%s</a>' % ('/', 'Vietnam')]
		for loc in supers:
			links.append('<a href="%s">%s</a>' % (loc.path, loc.name))
		self.crumb = ' > '.join(links)
		super(Location, self).save(*args, **kwargs)
	
	def getfullname(self):
		if not self.local_name:
			return self.name
		else:
			return '%s (%s)' % (self.name, self.local_name)
# Custom manager for this Top class
class TopSortedManager(models.Manager):
	pass

from  itertools import chain	
		
class Top(models.Model):
	name = models.CharField(max_length=256)
	local_name = models.CharField(max_length=256, blank=True, null=True)
	location = models.ForeignKey(Location)
	owner = models.ForeignKey(User, blank = True, related_name = 'tops')
	added = models.DateTimeField(auto_now_add=True)
	vote = models.ManyToManyField(User, related_name = 'vote', blank=True, null=True)
	vote_count = models.IntegerField(default = 0)
	updated = models.DateTimeField(auto_now=True)
	
	def __unicode__(self):
		return self.name
	
	#Get Top List, sort by LTD
	#Get Top List out of 24 hours time frame, sort by #Top, then LTD
	#Limit by 50
	@classmethod
	def get_sorted(cls):
		last24h = datetime.strftime( datetime.now() - timedelta(days=1), '%Y-%m-%d')
		q1 = cls.objects.filter( updated__gte = last24h).order_by('-updated')
		q2 = cls.objects.filter( updated__lt = last24h).order_by('-vote_count')
		return chain (q1, q2)

import urllib2
from StringIO import StringIO
from django.core.files.base import ContentFile
class Pin(models.Model):
	name = models.CharField(max_length=256)
	url = models.URLField()
	image_url = models.URLField()
	top = models.ForeignKey(Top)
	owner = models.ForeignKey(User)
	image_cache = ImageField(upload_to = 'pin', blank = True)
	added = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	
	def save(self, *args, **kwargs):
		if self.image_url:
			input_file = StringIO(urllib2.urlopen(self.image_url).read())
			filename = '%s_%s_%s' % (slugify(self.name), datetime.strftime(datetime.now(),'%h%m%s'), os.path.basename(self.image_url))
			self.image_cache.save(filename, ContentFile(input_file.getvalue()), save=False)
			super(Pin, self).save(*args, **kwargs)

	def __unicode__(self):
		return self.name

class Comment(models.Model):
	content = models.TextField()
	owner = models.ForeignKey(User)
	added = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return ( '%s: %s...' % (self.owner.username, (self.content[:17] if len(self.content)>=20 else self.content) ) ) 
	
	class Meta:
		abstract = True

class CommentTop(Comment):
	top = models.ForeignKey(Top)
	
class CommentPin(Comment):
	pin = models.ForeignKey(Pin)
	

frontend/forms.py
# -*- coding: utf-8 -*-
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions


class CreateUserForm(forms.Form):
	text_input = forms.CharField()

	textarea = forms.CharField(
		widget = forms.Textarea(),
	)

	radio_buttons = forms.ChoiceField(
		choices = (
			('option_one', "Option one is this and that be sure to include why it's great"), 
			('option_two', "Option two can is something else and selecting it will deselect option one")
		),
		widget = forms.RadioSelect,
		initial = 'option_two',
	)

	checkboxes = forms.MultipleChoiceField(
		choices = (
			('option_one', "Option one is this and that be sure to include why it's great"), 
			('option_two', 'Option two can also be checked and included in form results'),
			('option_three', 'Option three can yes, you guessed it also be checked and included in form results')
		),
		initial = 'option_one',
		widget = forms.CheckboxSelectMultiple,
		help_text = "<strong>Note:</strong> Labels surround all the options for much larger click areas and a more usable form.",
	)

	appended_text = forms.CharField(
		help_text = "Here's more help text"
	)

	prepended_text = forms.CharField()

	prepended_text_two = forms.CharField()

	multicolon_select = forms.MultipleChoiceField(
		choices = (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')),
	)

	# Uni-form
	helper = FormHelper()
	helper.form_class = 'form-horizontal'
	helper.layout = Layout(
		Field('text_input', css_class='input-xlarge'),
		Field('textarea', rows="3", css_class='input-xlarge'),
		'radio_buttons',
		Field('checkboxes', style="background: #FAFAFA; padding: 10px;"),
		AppendedText('appended_text', '.00'),
		PrependedText('prepended_text', '<input type="checkbox" checked="checked" value="" id="" name="">', active=True),
		PrependedText('prepended_text_two', '@'),
		'multicolon_select',
		FormActions(
			Submit('save_changes', 'Save changes', css_class="btn-primary"),
			Submit('cancel', 'Cancel'),
		)
	)

frontend/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import  get_object_or_404, redirect, render
from frontend.models import Top, Location
#from django.contrib.auth.decorators import login_required
from django.contrib.messages.api import get_messages
from social_auth.views import setting
from django.contrib.auth import logout
	
def home(request):
	template_name = "frontend/top_list.html"
	data = { 
			'top_list': Top.get_sorted(),
			}
	return render(request, template_name, data)

def local(request):
	path = '/%s/' %  '/'.join([t for t in request.path.lower().split('/') if t])
	location = get_object_or_404(Location, path=path)
	template_name = "frontend/local.html"
	data = {'location': location}
	return render(request, template_name, data)

def accountscreateuser(request):
	name = setting('SOCIAL_AUTH_PARTIAL_PIPELINE_KEY', 'partial_pipeline')
	if request.method == 'POST' and request.POST.get('username'):
		request.session['saved_username'] = request.POST['username']
		avatar_file = request.FILES.get('avatar_file')
		if avatar_file:
			from django.core.files.base import ContentFile	
			from django.core.files.storage import default_storage
			avatar_url = default_storage.save(avatar_file.name, ContentFile(avatar_file.read())) 
		else:
			avatar_url = request.POST.get('avatar_url') 
		request.session['avatar_url'] = avatar_url
		backend = request.session[name]['backend']
		return redirect('socialauth_complete', backend=backend)
	else:
		response = request.session[name].get('kwargs').get('response')
		authid = response.get('id')
		if authid:
			backend = request.session[name].get('backend')
			if backend == 'facebook':
				avatar = "http://graph.facebook.com/%s/picture?type=large" % response["id"]
			elif backend == 'google':
				avatar = response.get("picture")
			elif backend == 'twitter':
				avatar = response.get("profile_image_url")
		return render(request, 'frontend/accounts/createuser.html', {'avatar': avatar} )

def accountserror(request):
	messages = get_messages(request)
	print messages, dir(messages)
	return render(request, 'frontend/accounts/error.html', {'messages': messages})

def accountslogout(request):
	"""Logs out user"""
	logout(request)
	return redirect('frontend_home')


frontend/templates/frontend/about.html
{% extends "frontend/site_base.html" %}
{% block main %}
<div class="span6 offset3" style="margin-top: 50px;">
	<address>
		<strong> All enquiries please email to:</strong>
		<br/>
		<br/>
		<a href="mailto:contact@topsnam.com">contact@topsnam.com</a>
	</address>
</div>
{% endblock main %}

frontend/templates/frontend/bignumber.html
{% extends "frontend/site_base.html" %}

{% block left_panel %}

{% endblock %}

{% block components %}
	<div class="best">
		<a href="#"><span class="number"><span>1</span></span>
			<span class="btext">Rice</span>
		</a>
		<div class="social">
			<a href="#" class="best">Best | 20 voted</a>
			<!-- <div class="fb-like" data-href="http://bocation.com/can tho/rice" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
			<a href="https://twitter.com/share" class="twitter-share-button" data-lang="en">Tweet</a> -->
		</div>
	</div>
	<div class="best">
		<a href="#"><span class="number"><span>2</span></span>
			<span class="btext">Lau Mam</span>
		</a>
	</div>
	<div class="best">
		<a href="#"><span class="number"><span>3</span></span>
			<span class="btext">Drink Beer on The River Side</span>
		</a>
	</div>
{% endblock %}

frontend/templates/frontend/comment.htm
{% load thumbnail %}
<div class="comment clearfix">
	<div class="smallavatar">
	    <a href="javascript:void(0)" class="imglink">
	    	{% thumbnail comment.owner.userprofile.avatar "50x50" crop="center" quality=99 as im %}
	        	<img src="{{ im.url }}" alt="Picture of {{ comment.owner.username }}">
	        {% endthumbnail %}
	    </a>
   </div>
   <div class="commentcontent">
		<a href="/">{{ comment.owner.first_name }} {{ comment.owner.last_name }} </a>{{ comment.content }}
	</div>
 </div>

frontend/templates/frontend/contact.html
{% extends "frontend/site_base.html" %}
{% block main %}
<div class="span6 offset3"  style="margin-top: 50px;">
	<address>
		<strong> All enquiries please email to:</strong>
		<br/>
		<br/>
		<a href="mailto:contact@topsnam.com">contact@topsnam.com</a>
	</address>
</div>
{% endblock main %}

frontend/templates/frontend/local.html
{% extends "frontend/top_list.html" %}
{% block headline %}
	<div class="alert alert-info">
        Top Things in {{ location.getfullname }}
        {% if location.superordinate %}
                - a {{ location.zoom.name }} of <a href="{{ locatioin.superordinate.path }}">{{ location.superordinate.getfullname }}</a>
        {% else %}
                - a city of <a href="/">Vietnam</a>
        {% endif %}
	</div>
{% endblock headline %}
{% block new_top %}
	<div class="newtopwrap well">
		<div class="newtop">
			<img src="{{ STATIC_URL }}images/greyplus.png">
			<span>Add new top thing for {{ location.getfullname }}</span>
		</div>
		<form class="newtopform form-horizontal">
			<div class="close">×</div>
			<div class="control-group">
				<label class="control-label">What is the good thing?</label>
				<div class="controls"> 
					<input type="text" name="name"/>
					<input type="submit" class="btn btn-primary" value="Submit New Top" />
				</div>
			</div>
			<div class="control-group" style="margin-bottom:0px;">
				<label class="control-label">How local say it? (optional)</label>
				<div class="controls"> 
					<input type="text" name="localname"/>
				</div>
			</div>
			<input type="hidden" name="locationid" value="{{ location.id }}" />
		</form>
	</div>
{% endblock new_top %}

{% block top_list %}
	{% for top in location.get_sorted_tops %}
		{% include "frontend/topboard.htm" %}
	{% endfor %}
{% endblock top_list %}

frontend/templates/frontend/pincrumb.htm
{% load thumbnail %}
<div class="thumb75">
	{% thumbnail pin.image_cache "75x75" crop="center" quality=99 as im %}
	    <a href="{% url frontend_pingetdetails id=pin.id %}" title="{{ pin.name }}">
	    	<img src="{{ im.url }}">
	    </a>
	{% endthumbnail %}
</div>

frontend/templates/frontend/pindetails.htm
{% load thumbnail %}

<div class="modal-header">  
	<a class="close" data-dismiss="modal">×</a>  
	{% if pin.url %}<h3><a target="_blank" href="{{ pin.url }}" class="externallink">{{ pin.name }}</a></h3>{% else %}<h3>{{ pin.name }}</h3>{% endif %}  
</div>  
<div class="modal-body">  
	<div class="pincontent">
		{% if site == "youtube" %}
			<iframe width="420" height="315" src="http://www.youtube.com/embed/{{ youtube_id }}" frameborder="0" allowfullscreen>
			</iframe>
		{% else %}
			<img src={{ pin.image_url }}>
		{% endif %}
	</div>
	<div class="pinattribution">
		{% for comment in pin.commentpin_set.all %}
			{% include "frontend/comment.htm" %}
	    {% endfor %}
	 
		<form class="write comment">
			<div class="smallavatar">
	            <a href="javascript:void(0)" class="imglink">
	            	{% thumbnail request.user.userprofile.avatar "50x50" crop="center" quality=99 as im %}
	            		<img src="{{ im.url }}" alt="Picture of {{ request.user.username  }}">
	                {% endthumbnail %}
	            </a>
	       </div>
	       <div class="commentcontent">
	            <form class="commentform">
	            	<input name="pinid" type="hidden" value="{{ pin.pk }}" />
	                <textarea name="content" class="newcomment" maxlength="1000" placeholder="Add you comment..."></textarea>
	    			<input type="submit" class="btn" value="Comment"/>
	            </form>
	       </div>
	     </form>
	</div>
</div>  
<div class="modal-footer">  
<a href="javascript:void(0)" class="btn" data-dismiss="modal">Close</a>  
</div>  

frontend/templates/frontend/pinthumbs.htm
<div class="slides">
	{% for thumb in thumbs %}
		<img src="{{ thumb }}" style="width: 170px; height: 170px;">
	{% endfor %}
</div>
{% if site == "youtube" %}
	<i style="background: url('{{ STATIC_URL}}images/play.png');bottom: 30px; width: 35px; height: 26px; position: absolute;"></i>
{% endif %}

frontend/templates/frontend/site_base.html
{% extends "base.html" %}
{% block head %}
    <!-- Le styles -->
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/topsnam.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
{% endblock head %}

{% block content %}
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container-fluid">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      {% block navbarleft %}
		      {% if user.is_authenticated %}
			      <div class="btn-group pull-right">
			        <a class="btn dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">
			          <i class="icon-user"></i> {{ user.username }}<span class="caret"></span>
			        </a>
			        <ul class="dropdown-menu">
			          <li><a href="javascript:void(0)">Profile</a></li>
			          <li class="divider"></li>
			          <li><a href="{% url frontend_accountslogout %}">Sign Out</a></li>
			        </ul>
			      </div>
			  {% else %}
			      <div class="btn-group pull-right">
			        <a class="btn" rel="nofollow" href="{% url socialauth_begin 'facebook' %}">
			          <i class="icon-facebook"></i> Sign In with FaceBook</a>
			      </div>
			  {% endif %}
	      {% endblock navbarleft %}
	      <div class="nav-collapse">
	        <ul class="nav">
	          <li class="active"><a href="{% url frontend_home %}">Home</a></li>
	          <li class="active"><a href="{% url frontend_about %}">About</a></li>
	          <li class="active"><a href="{% url frontend_contact %}">Contact</a></li>
	        </ul>
	      </div><!--/.nav-collapse -->
	      <a class="brand" href="{% url frontend_home %}"></a>
	    </div>
	  </div>
	</div><!--/ .navbar -->
	{% block main %}
	{% endblock main %}
{% endblock content %}
{% block extra_content %}
<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=245401445484117";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
//Google Analytics
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26122686-3']);
  _gaq.push(['_setDomainName', 'topsnam.com']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% endblock extra_content %}

frontend/templates/frontend/top_list.html
{% extends "frontend/site_base.html" %}
{% block extra_head %}
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script> 
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ui.map.full.3.0RC.min.js"></script>
	<script type="text/javascript">
		{% include "frontend/topsnam.js" %}
	</script>
{% endblock extra_head %}
{% block main %}
	<div class="container-fluid">
	  <div class="row-fluid">
	    <div class="span3">
	      <div class="well sidebar-nav">
	      	<div id="map"></div>
	      </div><!--/.well -->
	    </div><!--/span-->	
	    <div class="span9">
	    	 {% block headline %}
				<div class="alert alert-info">Top Things in Vietnam</div>
			  {% endblock headline %}	
			<div class="tophead">
				{% block new_top %}
				{% endblock new_top %}
	    	</div>
	    	{% block top_list %}
				{% for top in top_list %}
					{% if forloop.first %}
						<script type="text/javascript">
							var toploc = {{ top.location.pk }};
						</script>
					{% endif %}
					{% include "frontend/topboard.htm" %}
				{% endfor %}
			{% endblock top_list %}
	    </div><!--/span9-->
	  </div><!--/row-fluid-->
	</div><!--/container-fluid-->
	<div id="modal" class="modal hide fade in" style="display: none;"></div>  
{% endblock main %}

frontend/templates/frontend/topboard.htm
{% load thumbnail %}

<div class="top well">
	<div class="row-fluid">
		<h2 class="topname span10">
			{{ top.name }}
			{% if top.local_name %}<span><span class="label label-info translate">local translation</span><span class="toplocalname">({{ top.local_name }})</span></span>{% endif %}
		</h2>
		<form class="topit span2" style="display:none;">
			<input name="topid" type="hidden" value= {{ top.pk }} />
			<input type="submit" value="Top It" class="topsubmit"/>
		</form>			
	</div>
	{% if not location  %}
	<div class="local">
		{% if forloop.first %}
			<img src="{{ STATIC_URL }}images/reddot.png" style="vertical-align: middle;">
		{% endif %}
		{{ top.location.crumb|safe }}
	</div>
	{% endif %}
	<div class="row-fluid">
			<div class="preview span8">
				<div class="crumb row-fluid">
					{% for pin in top.pin_set.all %}
						{% include "frontend/pincrumb.htm" %}						
					{% endfor %}
					<div class="thumb75 wait" style="text-align:center; display: none;">
						<span style="height: 100%; vertical-align: middle; display: inline-block;"></span>
				    	<img src="{{ STATIC_URL }}images/loading1.gif" style="width:30px;height:30px;vertical-align: middle; display:inline-block;"/>
					</div>
				</div>
				<form class="form-inline pinform">
					<label>Enter URL</label>
					<input name='pinurl' type="text" class="pinurl" placeholder="http://" />
					<input type="submit" class="btn" value="Get Images"/>
				</form>
				<form class="imageform row-fluid">
					<div class="span6">
						<div class="imagepicker">
							<div class="wait" style="text-align:center; display: none;">
								<span style="height: 100%; vertical-align: middle; display: inline-block;"></span>
						    	<img src="{{ STATIC_URL }}images/loading1.gif" style="width:30px;height:30px;vertical-align: middle; display:inline-block;"/>
							</div>
						</div>
					</div>
					<input type="hidden" value="" name="url" />
					<input type="hidden" value="" name="image_url" />
					<input type="hidden" value="{{ top.id }}" name="topid" />
			        <textarea name="name" class="pindesc span6" placeholder="Describe your pin..."></textarea>
			        <input type="submit" class="btn" value="Pin It!" />
				</form>
			</div>
			
			<div class="divider"></div>
			<div class="attribution span4">
				{% for comment in top.commenttop_set.all %}
					{% include "frontend/comment.htm" %}
	            {% endfor %}
				<form class="write comment">
					<div class="smallavatar">
		                <a href="javascript:void(0)" class="imglink">
		                	{% thumbnail request.user.userprofile.avatar "50x50" crop="center" quality=99 as im %}
		                		<img src="{{ im.url }}" alt="Picture of {{ request.user.username  }}">
		                    {% endthumbnail %}
		                </a>
		           </div>
		           <div class="commentcontent">
		                <form class="commentform">
		                	<input name="topid" type="hidden" value="{{ top.pk }}" />
		                    <textarea name="content" class="newcomment" data-topid="{{ top.id }}" id="commenttop-{{ top.id }}" maxlength="1000" placeholder="Add your comment..."></textarea>
		        			<input type="submit" class="btn" value="Comment"/>
		                </form>
		           </div>
	             </form>
			</div>
	</div>

</div>